
CREATE PROCEDURE PRODUCTION.usp_UpdatePRODUCTDETAILSPRODUCTION.usp_UpdatePRODUCTDETAILS
AS  
MERGE PRODUCTION.PRODUCTDETAILS AS target  
USING (SELECT [PRODUCTID] , [DETAILS]	FROM [STAGE].[OData_PRODUCTDETAILS]) AS source
ON (source.[PRODUCTID] = target.[PRODUCTID])  
WHEN NOT MATCHED THEN INSERT ([PRODUCTID] , [DETAILS]) VALUES ([PRODUCTID] , [DETAILS]);
GO  