CREATE PROCEDURE PRODUCTION.usp_UpdatePERSONS
AS  
MERGE PRODUCTION.PERSONS AS target  
USING (SELECT [ID] , [NAME] FROM [STAGE].[OData_Persons]) AS source
ON (source.ID = target.ID)  
WHEN NOT MATCHED THEN INSERT ([ID] , [NAME] ) VALUES ([ID] , [NAME] );
GO  
